In [1]:
import pandas as pd

In [2]:
# 五粮液 000858
# 格力电器 000651
# 美的集团 000333

In [12]:
raw_df = pd.read_csv('../input/000858_CONSOLIDATED.csv')
raw_df.columns = [col.lower() for col in raw_df.columns]
raw_df = raw_df.sort_values(by='report_date', ascending=False)
raw_df.head()

,security_code,security_name_abbr,report_date,total_assets,fixed_asset,monetaryfunds,monetaryfunds_yoy,accounts_rece,accounts_rece_yoy,inventory,...,deduct_basic_eps,weightavg_roe,operate_income_yoy,netprofit_yoy,book_value_per_share,netcash_operate_per_share,gross_margin,operate_income_mom,netprofit_mom,qdate
1,858,五粮液,2023-09-30 00:00:00,1.518034e+11,5.250182e+09,9.814771e+10,23.727348,1.406224e+08,10.382347,1.562720e+10,...,NaN,19.20,12.113192,14.24,31.476796,5.767905,75.859228,18.5312,28.9590,2023Q3
2,858,五粮液,2023-06-30 00:00:00,1.505734e+11,5.255604e+09,9.255730e+10,22.882954,7.857872e+07,-36.097269,1.609827e+10,...,4.364,14.19,10.392431,12.83,29.983544,2.918847,76.776972,-53.8598,-64.1637,2023Q2
4,858,五粮液,2023-03-31 00:00:00,1.604211e+11,5.254760e+09,1.011283e+11,28.742068,8.845112e+07,-50.377978,1.606515e+10,...,NaN,10.43,13.034273,15.89,32.607616,2.456615,78.394648,71.1966,87.1583,2023Q1
0,858,五粮液,2022-12-31 00:00:00,1.528119e+11,5.312971e+09,9.235843e+10,12.172654,3.568694e+07,-44.406902,1.598066e+10,...,6.869,25.28,11.719828,14.17,29.376459,6.294076,75.424145,24.9472,37.0303,2022Q4
5,858,五粮液,2022-09-30 00:00:00,1.346845e+11,5.412998e+09,7.932580e+10,8.433757,1.273957e+08,9.430902,1.496139e+10,...,NaN,19.25,12.185825,15.36,27.649297,2.778611,75.972720,6.4581,14.3667,2022Q3

In [17]:
# ROE
# 1. roe
# 2. net margin
# 3. asset turnover
# 4. financial leverage
raw_df['net_margin'] = raw_df['parent_netprofit'] / raw_df['total_revenue']
raw_df['total_asset_turnover'] = raw_df['total_revenue'] / raw_df['total_assets']
raw_df['financial_leverage'] = raw_df['total_assets'] / raw_df['total_liabilities']

# quality
# 1. operate cash inflow to revenue
# 2. operate net cash flow to net profit
# 3. free cash flow
raw_df['cash_to_revenue'] = raw_df['sales_services'] / raw_df['total_revenue']
raw_df['cfo_to_netprofit'] = raw_df['netcash_operate'] / raw_df['operate_profit']
raw_df['free_cash_flow'] = raw_df['sales_services'] - raw_df['construct_long_asset']

# activity ratios
raw_df['days_sales_receivables'] = raw_df['accounts_rece'] / raw_df['total_revenue'] * 365
raw_df['days_inventory_on_hands'] = raw_df['inventory'] / raw_df['operate_cost'] * 365
raw_df['days_sales_payables'] = raw_df['accounts_payable'] / raw_df['operate_cost'] * 365
raw_df['fixed_asset_turnover'] = raw_df['total_revenue'] / raw_df['fixed_asset']

# liquidity ratios
raw_df['cash_conversion_cycle'] = raw_df[
    'days_sales_receivables'] + raw_df['days_inventory_on_hands'] - raw_df['days_sales_payables']
# solvency ratios
# profitability ratios
raw_df['return_on_asset'] = raw_df['parent_netprofit'] / raw_df['total_assets']

raw_df.head()

,security_code,security_name_abbr,report_date,total_assets,fixed_asset,monetaryfunds,monetaryfunds_yoy,accounts_rece,accounts_rece_yoy,inventory,...,net_margin,total_asset_turnover,financial_leverage,cash_to_revenue,cfo_to_netprofit,free_cash_flow,days_sales_receivables,days_inventory_on_hands,days_sales_payables,fixed_asset_turnover
1,858,五粮液,2023-09-30 00:00:00,1.518034e+11,5.250182e+09,9.814771e+10,23.727348,1.406224e+08,10.382347,1.562720e+10,...,0.365114,0.411957,5.588524,1.068474,0.706624,6.437533e+10,0.820757,377.824381,180.216739,11.911281
2,858,五粮液,2023-06-30 00:00:00,1.505734e+11,5.255604e+09,9.255730e+10,22.882954,7.857872e+07,-36.097269,1.609827e+10,...,0.374381,0.302221,4.892170,0.946058,0.477738,4.170664e+10,0.630268,556.007740,263.021426,8.658640
4,858,五粮液,2023-03-31 00:00:00,1.604211e+11,5.254760e+09,1.011283e+11,28.742068,8.845112e+07,-50.377978,1.606515e+10,...,0.402779,0.194107,5.237791,0.919650,0.545759,2.753264e+10,1.036796,871.592891,406.499425,5.925839
0,858,五粮液,2022-12-31 00:00:00,1.528119e+11,5.312971e+09,9.235843e+10,12.172654,3.568694e+07,-44.406902,1.598066e+10,...,0.360838,0.484050,4.230100,1.105476,0.657203,7.999005e+10,0.176098,320.871561,145.506714,13.922273
5,858,五粮液,2022-09-30 00:00:00,1.346845e+11,5.412998e+09,7.932580e+10,8.433757,1.273957e+08,9.430902,1.496139e+10,...,0.358325,0.414151,5.388129,0.878894,0.386653,4.753113e+10,0.833627,407.459121,207.292229,10.304768